# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a04ef7263969c3d0fa3e43589f4774b0961bfe0e21a58386bc0e4757c00683bbe778a7463d5c3dda454d0586327714fbc65acfbf11ffe1ad4f1905be38df88b2

test:
  secret_key_base: 30ee96a1bd25ef6b86d638f32f6306f70d5a26da20d9d7fabd206cacc9a93676807d9272d64e9f421e48812868ab46cefc554ea78ec553920b1400a0c4f63afc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
